Jenkinsfile, releng/org.polarsys.capella.transition.system2subsystem.target/tp/capella.target-definition.targetplatform
Change-Id: Iad1a010e7a43db0c06caf98e40d9190add85438c
Signed-off-by: Sandu Postaru <sandu.postaru@thalesgroup.com>
=> [releng] Add Jenkinsfile

Jenkinsfile, plugins/org.polarsys.capella.transition.system2subsystem.crossphases/src/org/polarsys/capella/transition/system2subsystem/crossphases/rules/cs/PartRule.java, plugins/org.polarsys.capella.transition.system2subsystem.crossphases/src/org/polarsys/capella/transition/system2subsystem/crossphases/rules/la/LogicalComponentRule.java, plugins/org.polarsys.capella.transition.system2subsystem.crossphases/src/org/polarsys/capella/transition/system2subsystem/crossphases/rules/pa/Component2SARule.java, plugins/org.polarsys.capella.transition.system2subsystem.multiphases/src/org/polarsys/capella/transition/system2subsystem/multiphases/rules/PartRules.java, plugins/org.polarsys.capella.transition.system2subsystem.multiphases/src/org/polarsys/capella/transition/system2subsystem/multiphases/rules/PhysicalComponentRules.java, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/Project_test_01/Project_test_01.melodymodeller, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/mixed/AllMixedTests.java, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/mixed/PropertyValuesTest.java, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/multiphases/AllMultiPhasesTests.java, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/multiphases/SubPhyscialComponent.java, releng/org.polarsys.capella.transition.system2subsystem.target/tp/capella.target-definition.targetplatform
Bug 560557 - Link to PV contained in Component is lost in a Cross-phase
sub-system transition
and
Bug 560558 - [Multi phases transition] Transition a sub Physical
Component creates 2 Physical Systems
Change-Id: Ic8dd0fc4339b304f985bc2930ce6b5b43d1534e3
Signed-off-by: Tu Ton <minhtutonthat@gmail.com>
=> [560557 and 560558] This commit fixes 2 bugs:

Jenkinsfile, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/568503/.project, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/568503/568503.afm, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/568503/568503.aird, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/568503/568503.melodymodeller, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/mixed/AllMixedTests.java, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/mixed/TestComposite568503.java, plugins/org.polarsys.capella.transition.system2subsystem/plugin.xml, plugins/org.polarsys.capella.transition.system2subsystem/src/org/polarsys/capella/transition/system2subsystem/handlers/attachment/FunctionalChainAttachmentHelper.java, plugins/org.polarsys.capella.transition.system2subsystem/src/org/polarsys/capella/transition/system2subsystem/rules/fa/AbstractFunctionRule.java, plugins/org.polarsys.capella.transition.system2subsystem/src/org/polarsys/capella/transition/system2subsystem/rules/fa/FunctionalChainInvolvementLinkRule.java, plugins/org.polarsys.capella.transition.system2subsystem/src/org/polarsys/capella/transition/system2subsystem/rules/fa/FunctionalChainInvolvementRule.java, plugins/org.polarsys.capella.transition.system2subsystem/src/org/polarsys/capella/transition/system2subsystem/rules/fa/FunctionalChainRule.java
Change-Id: Ie1370225747b10da521f0c1c0184c2fb6cf353c2
=> [568503] Composite chains are not always correctly propagated

plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/Project_test_01/Project_test_01.melodymodeller, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/mixed/FunctionalChainTest.java, plugins/org.polarsys.capella.transition.system2subsystem/plugin.xml, plugins/org.polarsys.capella.transition.system2subsystem/src/org/polarsys/capella/transition/system2subsystem/rules/fa/ControlNodeRule.java
Bug: 568897
Change-Id: I7bb042876fe10655d476f7b79b752e7857e29360
Signed-off-by: Tu Ton <minhtutonthat@gmail.com>
=> [568897] Invalid Sequence Links and Control Nodes should not be transitioned

Jenkinsfile, pom.xml
Change-Id: I7566f46a2700a62221c15081dda053da590ab6d1
=> [releng] Enable jacoco coverage on tests

Jenkinsfile
Change-Id: Ifcc6e6efc8c5146ceec3833152884d1b4a5e923c
=> [releng] Enable JUnits on main branches

plugins/org.polarsys.capella.transition.system2subsystem.multiphases/src/org/polarsys/capella/transition/system2subsystem/multiphases/activities/InitializeMultiphasesDiffMergeActivity.java, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/FakeExchangeChain/.project, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/FakeExchangeChain/FakeExchangeChain.afm, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/FakeExchangeChain/FakeExchangeChain.aird, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/FakeExchangeChain/FakeExchangeChain.melodymodeller, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/mixed/AllMixedTests.java, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/mixed/FakeExchangeChain.java, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/mixed/TestComposite568503.java, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/util/ChainHelper.java, plugins/org.polarsys.capella.transition.system2subsystem/src/org/polarsys/capella/transition/system2subsystem/activities/InitializeDiffMergeActivity.java, plugins/org.polarsys.capella.transition.system2subsystem/src/org/polarsys/capella/transition/system2subsystem/handlers/attachment/FunctionalChainAttachmentHelper.java, plugins/org.polarsys.capella.transition.system2subsystem/src/org/polarsys/capella/transition/system2subsystem/handlers/attachment/SubSets.java, plugins/org.polarsys.capella.transition.system2subsystem/src/org/polarsys/capella/transition/system2subsystem/handlers/filter/InvalidInvolvementLinks.java, plugins/org.polarsys.capella.transition.system2subsystem/src/org/polarsys/capella/transition/system2subsystem/rules/fa/FunctionalChainInvolvementRule.java
leaf involvments
Change-Id: I7bc30f9c6439c07995d118570b674fe050e61e51
=> #59 Created chains shall not involve successive functions or invalid

pom.xml
Change-Id: Ifc98f2bba6ce52b4cd0a39882be46e78accaf73c
Signed-off-by: Anita Matei Gabriel <matei.anita@thalesgroup.com>
=> Changed jar signer version to fix failing build

plugins/org.polarsys.capella.transition.system2subsystem.crossphases/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.crossphases/src/org/polarsys/capella/transition/system2subsystem/crossphases/rules/fa/FunctionalExchangeRule.java, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/mixed/AllMixedTests.java
Closes #64 
Change-Id: Ibc870cca3a316aa1beec7a943aa980f6bf6a7646
Signed-off-by: Anita Matei Gabriel <matei.anita@thalesgroup.com>
=> #64 Fixed transition bug of funct exchanges allocated to component exchanges, when they are inverted

plugins/org.polarsys.capella.transition.system2subsystem.crossphases/src/org/polarsys/capella/transition/system2subsystem/crossphases/rules/fa/FunctionalExchangeRule.java, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/mixed/PropertyValuesTest.java
Change-Id: I9b3c3959ef9365dcfaf61243c63dd20f205e9a8e
Signed-off-by: Anita Matei Gabriel <matei.anita@thalesgroup.com>
=> #64 Fixed some issues introduced in previous commits

plugins/org.polarsys.capella.transition.system2subsystem.doc/plugin.xml
Change-Id: I8d34bc6050ca12fa62f025b5d8efa490f64f0ab2
=> [doc] Cleanup unused TOC

plugins/org.polarsys.capella.transition.system2subsystem.crossphases/src/org/polarsys/capella/transition/system2subsystem/crossphases/rules/core/PropertyValueGroupRule.java, plugins/org.polarsys.capella.transition.system2subsystem.crossphases/src/org/polarsys/capella/transition/system2subsystem/crossphases/rules/core/PropertyValuePkgRule.java, plugins/org.polarsys.capella.transition.system2subsystem.crossphases/src/org/polarsys/capella/transition/system2subsystem/crossphases/rules/core/PropertyValueRule.java, plugins/org.polarsys.capella.transition.system2subsystem.multiphases/src/org/polarsys/capella/transition/system2subsystem/multiphases/handlers/traceability/config/RecTraceabilityHandler.java, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/Project_test_01/Project_test_01.capella, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/AbstractSystem2SubsystemTest.java, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/mixed/AllMixedTests.java, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/mixed/PropertyValuesTest.java
being transitioned
Change-Id: I057c45c58db6c4b3ecf440e8e98ebc9cceb702fc
Signed-off-by: Anita Matei Gabriel <matei.anita@thalesgroup.com>
=> #70 Solved a small issue where PV's in Data Pkg on OA level weren't

plugins/org.polarsys.capella.transition.system2subsystem.multiphases/src/org/polarsys/capella/transition/system2subsystem/multiphases/diffmerge/MultiphasesMatchPolicy.java
Change-Id: Ia5c21629cef4bac55d240365ff9ddba363c8b912
=> #70 Fixed multiphase transition of property values

plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/Project_test_01/Project_test_01.capella, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/pvmtmodel/.project, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/pvmtmodel/pvmtmodel.afm, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/pvmtmodel/pvmtmodel.aird, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/pvmtmodel/pvmtmodel.capella, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/AllSystem2SubsystemTests.java, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/mixed/PropertyValuesTest.java, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/util/SubSystemSessionHandlerTest.java, plugins/org.polarsys.capella.transition.system2subsystem/src/org/polarsys/capella/transition/system2subsystem/handlers/session/SubSystemSessionHandler.java
Change-Id: I59782e1a8d970eac9fa1c491be93640743afc128
=> #76 Fix iterativity on cross-interphase when source model contains SID

features/org.polarsys.capella.transition.system2subsystem.feature/feature.xml, features/org.polarsys.capella.transition.system2subsystem.tests.feature/feature.xml, features/pom.xml, plugins/org.polarsys.capella.transition.system2subsystem.crossphases.ui/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.crossphases/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.doc/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.interphases.ui/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.interphases/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.multiphases.ui/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.multiphases/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/pom.xml, plugins/org.polarsys.capella.transition.system2subsystem.ui/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem/META-INF/MANIFEST.MF, plugins/pom.xml, pom.xml, releng/org.polarsys.capella.transition.system2subsystem.site/category.xml, releng/org.polarsys.capella.transition.system2subsystem.site/pom.xml, releng/org.polarsys.capella.transition.system2subsystem.target/pom.xml
Change-Id: Icdeff9668b599217f6cb38034b9a8aab42af8348
=> [releng] Bump to 1.4.3

Jenkinsfile, plugins/org.polarsys.capella.transition.system2subsystem.multiphases/src/org/polarsys/capella/transition/system2subsystem/multiphases/activities/InitializeMultiphasesDiffMergeActivity.java, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/fragmentedOutput/.project, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/fragmentedOutput/fragmentedOutput.afm, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/fragmentedOutput/fragmentedOutput.aird, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/fragmentedOutput/fragmentedOutput.capella, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/fragmentedOutput/fragments/SA.airdfragment, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/model/fragmentedOutput/fragments/SA.capellafragment, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/crossphases/AllCrossPhasesTests.java, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/src/org/polarsys/capella/transition/system2subsystem/tests/crossphases/PhysicalToSystemComponent.java, plugins/org.polarsys.capella.transition.system2subsystem/src/org/polarsys/capella/transition/system2subsystem/activities/FinalizeSubsystemTransitionActivity.java, pom.xml, releng/org.polarsys.capella.transition.system2subsystem.target/pom.xml
=> #100 System to subsystem transition - not working with fragmented model

features/org.polarsys.capella.transition.system2subsystem.feature/feature.xml, features/org.polarsys.capella.transition.system2subsystem.tests.feature/feature.xml, features/pom.xml, plugins/org.polarsys.capella.transition.system2subsystem.crossphases.ui/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.crossphases/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.doc/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.interphases.ui/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.interphases/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.multiphases.ui/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.multiphases/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/pom.xml, plugins/org.polarsys.capella.transition.system2subsystem.ui/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem/META-INF/MANIFEST.MF, plugins/pom.xml, pom.xml, releng/org.polarsys.capella.transition.system2subsystem.site/category.xml, releng/org.polarsys.capella.transition.system2subsystem.site/pom.xml, releng/org.polarsys.capella.transition.system2subsystem.target/pom.xml
bump sss to 1.6.2
Change-Id: If7948e14a68220710272a3594c80aae91ade7c61
=> [releng] Bump to 1.6.2

plugins/org.polarsys.capella.transition.system2subsystem/src/org/polarsys/capella/transition/system2subsystem/activities/CopyManagementPropertiesActivity.java
Change-Id: Iefdb299f233f91e7a9a79f1dc072c73c0f39e1f0
=> #107 ClassCastException can happen when transitionning non-Capella element

Jenkinsfile, features/org.polarsys.capella.transition.system2subsystem.feature/feature.xml, features/org.polarsys.capella.transition.system2subsystem.tests.feature/feature.xml, features/pom.xml, plugins/org.polarsys.capella.transition.system2subsystem.crossphases.ui/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.crossphases/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.doc/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.interphases.ui/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.interphases/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.multiphases.ui/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.multiphases/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem.tests.ju/pom.xml, plugins/org.polarsys.capella.transition.system2subsystem.ui/META-INF/MANIFEST.MF, plugins/org.polarsys.capella.transition.system2subsystem/META-INF/MANIFEST.MF, plugins/pom.xml, pom.xml, releng/org.polarsys.capella.transition.system2subsystem.site/category.xml, releng/org.polarsys.capella.transition.system2subsystem.site/pom.xml, releng/org.polarsys.capella.transition.system2subsystem.target/pom.xml, releng/org.polarsys.capella.transition.system2subsystem.target/tp/capella.target-definition.targetplatform
Change-Id: Ic92f7310d113a6adb3e084f7b94f46892a160a71
=> [Releng] Bump to v1.6.3

CONTRIBUTING.md, NOTICE.md, plugins/org.polarsys.capella.transition.system2subsystem.doc/html/Installation and Uninstallation.html, plugins/org.polarsys.capella.transition.system2subsystem.doc/html/Installation and Uninstallation.mediawiki, plugins/org.polarsys.capella.transition.system2subsystem.doc/html/Release Notes/KnownIssues.html, plugins/org.polarsys.capella.transition.system2subsystem.doc/html/Release Notes/KnownIssues.mediawiki, plugins/org.polarsys.capella.transition.system2subsystem.doc/html/Release Notes/Whatsnew.html, plugins/org.polarsys.capella.transition.system2subsystem.doc/html/Release Notes/Whatsnew.mediawiki
=> #118 Changed links to /eclipse-capella
